replicaCount: 1
image:
  repository: thakkarpurvesh-xebia-97/${{values.app_name}}
  pullPolicy: IfNotPresent
  tag: ${{values.app_name}}-${{values.app_env}}-latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80 # React apps usually run on port 80
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: ${{values.app_name}}-${{values.app_env}}.test.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    cpu: 50m
    memory: 50M
livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}