apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.app_name}}
  labels:
    app: ${{values.app_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.app_name}}
  template:
    metadata:
      labels:
        app: ${{values.app_name}}
    spec:
      containers:
      - name: ${{values.app_name}}
        image: thakkarpurvesh-xebia-97/${{values.app_name}}:latest
        ports:
        - containerPort: 80